Save generated plots
Baukebrenninkmeijer/table-evaluator pull request #19
Opened 2021-11-18 04:19 UTC by vnykr

Hi, 

I have added the option to save the generated plots to a file based on the suggestions in Issue #14. Here are the changes I have made. 

**1. Add argument `fname` to the plotting functions**
If `fname` is specified then simply calls `plt.savefig(fname)` to save the plot result. 

**2. Add argument `save_dir` to `visual_evaluation()` function** 
If `save_dir` is specified then saves all generated plots into this directory. Each image has a fixed name in this case. 

Hope this is useful.

2021-11-29 21:05 UTC, Baukebrenninkmeijer commented
@vnykr Looks great! 

Could you make develop the target? That's the branch where it should be merged first, since I'm following a gitflow working method. Thanks!

2021-11-29 21:07 UTC, Baukebrenninkmeijer commented on table_evaluator/table_evaluator.py
> +            self.plot_mean_std(fname=os.path.join(save_dir, 'mean_std.png'))
Could you replace these `os.path.join` with 
```python
from pathlib import Path
save_dir = Path(save_dir)

self.plot_mean_std(fname=save_dir/'mean_std.png'
```

and the same for the other paths. I prefer working with the path library over os.path.join.

2021-11-29 21:08 UTC, Baukebrenninkmeijer requested changes
Just those filenames and I'm good. Please make sure to target develop :).

2021-11-30 09:24 UTC, vnykr commented
@Baukebrenninkmeijer My apologies for targeting the wrong branch, this is my first time making a pull request! 
I think I have made the correct changes, please let me know if there is anything else.

2021-11-30 16:11 UTC, merged